</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:11	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:14	1	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:34	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:%14
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:81	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:%outlen.09
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:99	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:%25
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:106	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:%55
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:34	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:%mbclen.0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:52	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:%40
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:17	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%len
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:40	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%23
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:60	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:64	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:111	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%66
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:163	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%103
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:223	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%144
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:226	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%144
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:251	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%indvars.iv.next89
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:253	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%indvars.iv.next89
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:273	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%176
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:323	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%203
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:376	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%231
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:379	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%231
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:41	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%21
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:62	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%43
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:107	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%indvars.iv.next42
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:121	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%indvars.iv39
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:124	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%85
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:132	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%91
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:146	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%indvars.iv37
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:271	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%indvars.iv43
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:274	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%183
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:276	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%indvars.iv43
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:291	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:294	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%195
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:296	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta:14	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta:%9
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext:15	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext:%11
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:40	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:45	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.pre
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:54	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum7.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:65	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%46
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:69	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum8.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:72	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%52
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:76	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum9.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:81	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum10.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:84	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%61
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:89	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum12.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:92	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%67
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:97	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum14.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:100	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%73
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:104	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum15.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:109	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum16.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:112	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%82
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:117	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum18.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:120	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%88
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:125	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum20.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:128	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%94
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:132	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum21.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:137	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum22.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:140	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%103
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:145	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum24.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:148	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%109
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:152	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum25.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:172	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%123
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:175	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum26.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:180	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%129
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:185	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%41
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:189	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%size
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:194	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%138
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:206	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%148
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:209	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum2.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:212	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%152
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:225	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum3.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:239	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum5.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:242	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum6.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:247	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum4.i
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:277	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%size
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:294	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum7.i1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:318	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%214
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:322	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%217
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:331	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%223
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:335	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%226
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:339	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum5.i2
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:343	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%232
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:347	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum6.i3
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:351	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%238
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:363	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%208
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:366	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum4.i4
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:370	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%248
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:382	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%255
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:406	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%265
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:463	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%287
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:480	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%302
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:483	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%.sum.i7
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:487	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%306
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:498	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%306
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:526	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%327
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:26	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:%10
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:52	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:%27
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:28	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%13
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:40	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%18
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:60	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%29
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:64	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%37
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:73	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%42
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:90	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%53
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:104	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%.sum7
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:109	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%.sum6
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:112	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%68
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:131	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%79
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:138	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%len.0
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:141	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%89
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:148	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%94
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:165	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%.sum5
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:176	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%114
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:182	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%.sum
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:185	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%117
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:61	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%24
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:99	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%48
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:315	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%223
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:412	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%290
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:463	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%321
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:524	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%364
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:577	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%396
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:654	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%451
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:757	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%520
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:790	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:802	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%552
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:844	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%indvars.iv235
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:858	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%591
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:958	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%653
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:999	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%682
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1049	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%714
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1142	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%773
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1201	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%810
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1226	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%len.0.ph99.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1234	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%len.0.ph99.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1241	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%len.0.ph99.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1270	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%853
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1302	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%874
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1363	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%917
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1423	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%957
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1462	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%982
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1504	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1008
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1558	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1043
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1610	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1074
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1662	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1106
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1681	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1117
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1725	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1149
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1804	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1202
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1817	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1213
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1831	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1222
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1844	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1230
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1869	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1939	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1284
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1999	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1323
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2032	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1345
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2128	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1414
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2164	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:%1428
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:32	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%19
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:73	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%48
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:97	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv87
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:121	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv85
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:125	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%76
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:130	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%81
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:139	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%87
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:144	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%91
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:149	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%91
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:159	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%105
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:169	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%111
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:174	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:175	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:184	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%111
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:192	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv87
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:215	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%.sum1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:219	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%142
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:224	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%147
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:233	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%153
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:238	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%157
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:243	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%157
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:253	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%171
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:263	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%177
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:268	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i6
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:269	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i6
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:278	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%177
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:297	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%204
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:316	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%216
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:326	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%.sum
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:327	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.next84
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:339	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%228
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:406	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv87
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:411	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv87
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:427	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv79
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:442	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv79
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:446	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv79
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:450	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i11
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:452	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i11
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:466	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv79
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:471	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv79
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:479	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv79
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:487	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv79
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:492	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i19
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:493	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i19
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:502	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv79
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:522	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv77
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:543	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%355
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:562	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%364
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:566	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%364
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:572	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.i16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:574	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv.next.i17
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:584	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%.pre-phi
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:586	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%.pre-phi
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:606	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:41	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%indvars.iv43
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:45	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%indvars.iv41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:54	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%35
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:73	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%49
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:76	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%indvars.iv41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:87	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%60
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:95	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%indvars.iv41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:102	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%72
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:120	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%84
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:123	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%indvars.iv39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:138	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:141	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:22	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%13
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:27	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%18
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:40	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%13
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:54	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%indvars.iv8.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:72	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:74	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%indvars.iv.next.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:86	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%18
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:95	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%18
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:113	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%18
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:120	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%18
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:122	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:139	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%94
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:155	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%101
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:159	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%101
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:166	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%indvars.iv.i5
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:168	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%indvars.iv.next.i6
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:179	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%101
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:181	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%101
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:191	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%18
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:29	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%index
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:30	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%induction5760
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:33	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%index
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:34	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%induction5760
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:61	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:63	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:73	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:77	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:81	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:86	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:93	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:100	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv37
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:102	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv37
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:107	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv37
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:109	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv37
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:150	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:157	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:168	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:170	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:186	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:189	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:192	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:194	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:195	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:215	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:218	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%144
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:222	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:239	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:246	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:32	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv203
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:46	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%18
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:62	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:73	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:89	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:91	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv201
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:93	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv201
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:97	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%54
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:106	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%62
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:116	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%70
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:124	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:133	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:135	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:140	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:143	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:158	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:178	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%107
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:182	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%107
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:189	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.i39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:191	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.next.i40
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:204	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%.pre-phi
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:206	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%.pre-phi
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:214	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:229	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%146
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:252	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:297	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv191
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:310	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%54
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:317	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:317	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%213
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:326	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:336	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:346	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:356	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:366	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:376	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:386	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:396	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:524	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:527	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%331
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:539	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%331
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:542	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:546	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:557	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%350
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:560	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%351
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:568	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%index
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:569	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%induction246273
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:570	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%index
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:571	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%induction246273
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:587	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.i50
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:588	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.i50
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:597	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%331
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:608	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv199
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:610	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%376
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:612	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%376
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:632	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%388
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:642	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%388
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:644	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%388
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:657	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:693	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv177
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:716	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.i46
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:718	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.i46
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:764	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%index251
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:776	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%index251
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:786	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv174
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:794	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv174
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:801	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%481
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:816	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv166
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:820	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv166
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:827	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv148
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:830	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%498
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:835	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv148
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:841	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%507
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:843	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv146
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:862	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%519
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:874	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%526
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:881	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%526
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:887	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.i24
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:889	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.next.i25
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:898	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%526
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:910	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%550
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:933	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv150
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:936	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%570
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:960	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv152
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:979	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%597
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:991	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%604
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:998	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%604
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1004	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1006	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv.next.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1015	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%604
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1037	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv166
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1037	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%634
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1048	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv154
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1068	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv166
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1068	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv156
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1070	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv156
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1080	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv158
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1112	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv166
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1112	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv163
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1126	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%689
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1131	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%689
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1137	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%689
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1154	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:27	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%6
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:28	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:43	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%index
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:44	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%induction7781
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:56	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%24
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:66	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:72	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%36
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:154	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%85
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:163	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%89
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:196	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%107
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:204	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%113
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:217	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%122
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:233	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%100
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:243	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%141
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:247	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%144
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:267	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%155
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:281	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%164
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:285	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%167
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:295	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%174
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:299	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%177
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:317	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%185
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:323	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%185
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:327	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%197
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:336	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%185
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:369	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%228
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:419	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%262
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:20	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.05
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:21	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.05
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:33	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.05
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:43	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.05
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:46	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.05
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:54	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.05
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:61	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.05
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:64	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.05
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:75	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.0.lcssa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:78	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.0.lcssa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:81	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%i.0.lcssa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:11	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:37	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%index
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:41	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%.sum82
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:69	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%indvars.iv43
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:103	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%35
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:113	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%42
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:127	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%35
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:133	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%55
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:140	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%35
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:167	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%78
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:173	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%83
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:203	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%indvars.iv41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:212	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:214	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%indvars.iv41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:218	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%113
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:229	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%122
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:231	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:250	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%134
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:262	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%141
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:269	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%141
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:275	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:277	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%indvars.iv.next.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:286	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%141
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:297	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:299	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%indvars.iv41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:302	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%168
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:316	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%176
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:322	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%181
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:15	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%indvars.iv13
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:20	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%indvars.iv13
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:25	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%indvars.iv13
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:28	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%indvars.iv13
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:43	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:47	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:50	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:57	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:71	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:82	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:106	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%indvars.iv11
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:157	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:161	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:172	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%131
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:175	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:179	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:184	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:188	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%28
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:35	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv154.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:38	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv154.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:41	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv154.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:44	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv154.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:65	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv152.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:95	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i.i.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:129	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i.i12.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:157	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next144.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:163	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv143.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:169	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%.lcssa.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:206	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%124
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:217	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%129
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:222	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%133
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:230	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%137
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:232	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next151.i31
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:244	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%j.0.lcssa.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:274	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.i90.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:314	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%187
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:320	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%i.02.i.i.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:362	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i.i18.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:375	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i7.i.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:398	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i12.i.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:408	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next39.i.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:429	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:470	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next142.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:503	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i25.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:636	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i.i31.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:702	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:716	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.next.i36.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:725	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:728	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:731	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:762	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:22	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:%indvars.iv15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:27	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:%indvars.iv15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:47	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:%indvars.iv13
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:71	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:76	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:15	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:19	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:23	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:27	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:32	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:35	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:40	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%24
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:52	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:55	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:60	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%36
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc:29	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc:%oldsize.02
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:35	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%indvars.iv.next.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:39	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%len
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:76	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%indvars.iv.next33
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:101	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%indvars.iv.next
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:112	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%indvars.iv.next31
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:118	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%63
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:144	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%81
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:148	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%84
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:8	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:17	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:38	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:40	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:42	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:46	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%35
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:56	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:60	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:84	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:97	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:109	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:123	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:144	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:157	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:167	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%35
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:172	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:179	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:187	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:196	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%148
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:196	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%151
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:203	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:207	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:215	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv29.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:222	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:225	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%174
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:228	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:232	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:239	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:243	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:248	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv27.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:252	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:256	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%196
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:259	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv27.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:273	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv25.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:277	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%15
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:281	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%217
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:284	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv25.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:297	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:301	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:302	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:304	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:308	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%130
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:313	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv23.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:317	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv23.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:335	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:350	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:355	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:7	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%5
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:41	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%17
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:51	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%24
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:65	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%17
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:71	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%37
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:78	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%17
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:99	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%47
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:104	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%47
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:108	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:110	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%indvars.iv.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:127	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%68
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:143	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%68
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:152	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%indvars.iv32
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:157	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%68
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:159	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%indvars.iv32
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:163	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:174	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%107
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:176	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:197	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%121
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:213	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%128
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:217	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%128
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:224	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%indvars.iv.i3
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:226	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%indvars.iv.next.i4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:237	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%128
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:239	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%128
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:251	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%68
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:253	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%indvars.iv32
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:256	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%160
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:263	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%68
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:58	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:62	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:36	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:%26
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:73	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:%54
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:41	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%indvars.iv.i.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:96	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%indvars.iv.i22.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:114	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%73
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:131	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%indvars.iv.i22.i
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:360	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%226
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:383	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%226
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:389	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%226
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:395	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%259
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:420	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%267
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:443	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%267
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:449	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%267
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:455	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:%300
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks:6	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks:%2
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:15	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:%indvars.iv
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:56	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:%35
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:32	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%25
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:49	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%38
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:57	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%43
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:68	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%43
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:79	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%43
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:90	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%68
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:103	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%77
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:118	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%88
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:145	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%indvars.iv.i1.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:176	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%59
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:236	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%88
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:242	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%.sum.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:413	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%181
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:425	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%keycc.0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:430	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%188
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:479	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%keycc.1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:505	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%244
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:511	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%keycc.1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:871	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%497
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:882	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%505
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:916	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%526
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:34	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:%27
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:46	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:%32
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:49	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:%32
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:137	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%.sum.i.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:245	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%save.0.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:251	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%.sum.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:266	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%.sum19.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:347	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%197
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:431	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%.sum
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:439	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%.sum20.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:69	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:%48
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:103	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:%45
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:105	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:%.sum
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:108	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:%71
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:6	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%2
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:14	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%9
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:78	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%.sum
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:85	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%.sum1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:89	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%2
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:92	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%7
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:107	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%74
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:132	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%.lcssa8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:23	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:%4
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:57	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:%.0.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:62	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:%.sum
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:64	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%40
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:69	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%42
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:142	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%.sum.i
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:179	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%115
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:183	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%119
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:192	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%127
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:203	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%131
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:40	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:%.sum105
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:47	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:%.sum138
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:51	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:%.sum140
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:72	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:%.sum
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:54	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:%31
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:57	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:%31
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:93	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:%61
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:97	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:%63
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:28	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%13
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:37	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%16
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:62	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%33
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:155	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:160	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:161	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:167	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:173	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%115
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:197	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%.sum.pn
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:206	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%137
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:218	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%150
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:223	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%153
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:235	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:240	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:242	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%171
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:246	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:256	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:261	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:267	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:273	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%i.035
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:279	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%201
