</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:1	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:1:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:10	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:10:@mbtolower.outalloc
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:18	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:18:@mbtolower.out
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:22	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:22:@mbtolower.out
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:38	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:38:@mbtolower.out
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:54	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:54:@mbtolower.outalloc
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:57	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:57:@mbtolower.out
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:116	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:116:@mbtolower.out
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:125	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:125:@mbtolower.out
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:7	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:7:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:39	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:39:@kwset
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:55	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:55:@kwset
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:12	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:12:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:17	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:17:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:48	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:48:@kwset
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:94	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:94:@match_words
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:98	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:98:@match_lines
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:157	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:157:@kwset
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:19	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:19:@syntax_bits_set
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:30	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:30:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:39	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:39:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:45	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:45:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:54	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:54:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:60	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:60:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:77	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:77:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:32	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:32:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:39	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:39:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:47	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:47:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:50	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:50:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:58	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:58:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:63	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:63:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:77	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:77:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:85	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:85:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:88	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:88:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:96	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:96:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:101	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:101:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:114	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:114:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:125	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:125:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:129	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:129:@lasttok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:135	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:135:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:138	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:138:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:147	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:147:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:153	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:153:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:166	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:166:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:172	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:172:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:185	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:185:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:193	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:193:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:202	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:202:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:210	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:210:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:218	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:218:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:226	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:226:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:234	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:234:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:242	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:242:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:248	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:248:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:259	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:259:@laststart
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:266	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:266:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:269	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:269:@laststart
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:274	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:274:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:285	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:285:@laststart
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:290	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:290:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:302	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:302:@laststart
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:307	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:307:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:311	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:311:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:313	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:313:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:390	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:390:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:398	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:398:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:401	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:401:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:409	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:409:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:414	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:414:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:428	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:428:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:441	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:441:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:449	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:449:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:452	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:452:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:460	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:460:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:465	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:465:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:478	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:478:@minrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:482	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:482:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:490	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:490:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:502	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:502:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:510	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:510:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:513	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:513:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:521	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:521:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:526	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:526:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:540	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:540:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:555	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:555:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:563	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:563:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:566	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:566:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:574	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:574:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:579	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:579:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:591	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:591:@maxrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:596	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:596:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:600	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:600:@minrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:607	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:607:@minrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:611	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:611:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:620	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:620:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:632	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:632:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:640	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:640:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:643	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:643:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:651	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:651:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:656	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:656:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:674	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:674:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:687	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:687:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:699	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:699:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:706	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:706:@parens
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:712	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:712:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:719	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:719:@parens
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:744	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:744:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:748	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:748:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:778	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:778:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:832	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:832:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:923	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:923:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:943	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:943:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:946	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:946:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:965	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:965:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:977	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:977:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:985	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:985:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:988	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:988:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:996	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:996:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1001	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1001:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1015	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1015:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1027	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1027:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1035	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1035:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1038	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1038:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1046	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1046:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1051	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1051:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1102	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1102:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1108	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1108:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1120	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1120:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1128	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1128:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1131	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1131:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1139	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1139:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1144	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1144:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1162	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1162:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1179	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1179:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1187	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1187:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1190	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1190:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1198	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1198:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1203	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1203:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1216	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1216:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1219	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1219:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1223	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1223:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1260	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1260:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1263	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1263:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1267	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1267:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1272	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1272:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1283	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1283:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1470	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1470:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1482	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1482:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1490	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1490:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1493	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1493:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1501	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1501:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1506	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1506:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1520	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1520:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1524	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1524:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1536	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1536:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1544	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1544:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1547	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1547:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1555	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1555:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1560	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1560:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1576	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1576:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1588	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1588:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1596	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1596:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1599	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1599:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1607	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1607:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1612	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1612:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1628	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1628:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1640	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1640:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1648	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1648:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1651	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1651:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1659	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1659:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1664	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1664:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1677	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1677:@cur_mb_len
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1678	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1678:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1683	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1683:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1687	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1687:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1691	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1691:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1703	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1703:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1711	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1711:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1714	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1714:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1722	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1722:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1727	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1727:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1795	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1795:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1806	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1806:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1821	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1821:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1849	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1849:@hard_LC_COLLATE
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1899	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1899:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1905	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1905:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1917	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1917:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1925	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1925:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1928	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1928:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1936	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1936:@lexptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1941	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1941:@lexleft
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1959	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1959:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2056	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2056:@using_utf8.utf8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2116	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2116:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2120	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2120:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2158	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2158:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:24	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:24:@dfastate.initialized
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:54	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:54:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:221	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:221:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:238	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:238:bitcast ([8 x i32]* @dfastate.newline to <4 x i32>*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:245	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:245:bitcast (i32* getelementptr inbounds ([8 x i32]* @dfastate.newline, i64 0, i64 4) to <4 x i32>*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:259	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:259:bitcast ([8 x i32]* @dfastate.letters to <4 x i32>*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:267	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:267:bitcast (i32* getelementptr inbounds ([8 x i32]* @dfastate.letters, i64 0, i64 4) to <4 x i32>*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:279	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:279:bitcast ([8 x i32]* @dfastate.letters to <4 x i32>*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:286	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:286:bitcast (i32* getelementptr inbounds ([8 x i32]* @dfastate.letters, i64 0, i64 4) to <4 x i32>*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:799	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:799:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1032	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1032:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1108	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1108:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:8	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:8:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:10	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:10:@dfaexec.sbit_init
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:178	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:178:@buf_end
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:191	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:191:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:195	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:195:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:200	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:200:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:224	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:224:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:226	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:226:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:254	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:254:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:256	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:256:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:345	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:345:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:347	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:347:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:397	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:397:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:399	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:399:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:2:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:19	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:19:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:32	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:32:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:42	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:42:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:45	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:45:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:53	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:53:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:60	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:60:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:63	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:63:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:77	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:77:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:80	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:80:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:19	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:19:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:121	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:121:@buf_end
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:168	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:168:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:172	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:172:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:317	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:317:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:321	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:321:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:170	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:170:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:742	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:742:@using_utf8.utf8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:55	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:55:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:59	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:59:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:66	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:66:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:70	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:70:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:76	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:76:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:122	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:122:@inputwcs
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:126	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:126:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:130	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:130:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:136	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:136:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:178	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:178:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:221	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:221:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:251	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:251:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:276	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:276:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:2:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:6	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:6:@mblen_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:59	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:59:@buf_end
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:132	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:132:@buf_begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:4	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:4:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:24	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:24:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:27	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:27:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:58	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:58:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:61	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:61:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:76	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:76:@depth
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:78	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:78:@depth
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:80	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:80:@depth
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:82	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:82:@depth
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:86	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:86:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:92	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:92:@depth
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:97	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:97:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:3:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:5	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:5:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:7	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:7:@wctok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:36	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:36:@cur_mb_len
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:53	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:53:@cur_mb_len
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:62	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:62:@using_utf8.utf8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:78	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:78:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:102	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:102:@syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:106	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:106:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:130	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:130:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:136	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:136:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:145	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:145:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:154	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:154:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:170	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:170:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:181	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:181:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:188	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:188:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:199	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:199:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:206	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:206:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:217	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:217:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:224	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:224:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:233	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:233:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:247	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:247:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:262	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:262:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:271	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:271:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:279	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:279:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:288	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:288:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:294	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:294:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:306	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:306:@tok
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:310	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:310:@minrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:311	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:311:@maxrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:315	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:315:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:327	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:327:@minrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:335	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:335:@minrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:344	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:344:@maxrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:357	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:357:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:368	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:368:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:380	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:380:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:407	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:407:@minrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:417	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:417:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:428	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:428:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:440	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:440:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:470	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:470:@maxrep
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:477	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:477:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:493	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:493:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:510	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:510:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:524	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:524:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:535	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:535:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks:3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks:3:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:2:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:41	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:41:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:44	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:44:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:2:@case_fold
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:3	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:3:@stderr
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:5	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:5:@program_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:7	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:7:@stderr
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:9	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:9:@program_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:13	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:13:@program_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:20	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:20:@program_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:22	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:22:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 1, i32 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:55	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:55:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:191	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:191:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 0, i32 1)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:193	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:193:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 0, i32 2)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:195	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:195:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 1, i32 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:198	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:198:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 0, i32 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:220	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:220:@optind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:229	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:229:@get_nondigit_option.prev_digit_optind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:252	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:252:@optind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:295	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:295:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:318	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:318:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:341	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:341:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:370	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:370:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:393	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:393:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:410	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:410:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:411	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:411:@argmatch_die
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:417	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:417:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:426	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:426:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:434	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:434:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:443	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:443:@stdin
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:453	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:453:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:497	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:497:@stdin
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:524	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:524:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:561	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:561:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:582	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:582:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:621	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:621:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:639	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:639:@excluded_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:646	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:646:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:649	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:649:@excluded_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:656	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:656:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:662	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:662:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:665	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:665:@excluded_directory_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:672	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:672:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:675	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:675:@included_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:682	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:682:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:685	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:685:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:690	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:690:@optarg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:695	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:695:@exit_on_match
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:697	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:697:@list_files
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:706	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:706:@count_matches
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:707	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:707:@done_on_match
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:717	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:717:@out_after
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:722	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:722:@out_before
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:727	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:727:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:842	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:842:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:843	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:843:@program_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:849	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:849:@show_help
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:858	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:858:@out_invert
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:867	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:867:@optind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:878	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:878:@optind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:890	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:890:@compile
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:893	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:893:@optind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:896	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:896:@no_filenames
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:905	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:905:@max_count
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:910	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:910:@optind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:919	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:919:@included_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:921	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:921:@excluded_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:928	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:928:@included_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:933	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:933:@excluded_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:959	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:959:@optind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:968	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:968:@errseen
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:3	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:3:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 0, i32 1)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:5	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:5:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 0, i32 2)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:7	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:7:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 1, i32 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:10	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:10:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 0, i32 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:13	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:13:@setmatcher.matcher
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:16	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:16:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 0, i32 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:22	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:22:getelementptr inbounds ([0 x %struct.matcher.10]* @matchers, i64 0, i64 1, i32 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:26	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:26:@program_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:27	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:27:@setmatcher.matcher
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:5	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:5:@label
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:18	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:18:@suppress_errors
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:26	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:26:@directories
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:34	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:34:@devices
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:50	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:50:@directories
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:64	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:64:@suppress_errors
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:73	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:73:@suppress_errors
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:94	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:94:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:99	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:99:@pagesize
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:102	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:102:@buffer
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:126	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:126:@pagesize
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:142	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:142:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:164	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:164:@directories
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:185	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:185:@max_count
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:201	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:201:@suppress_errors
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:203	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:203:@filename
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:208	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:208:@binary_files
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:209	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:209:@out_quiet
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:215	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:215:@bufbeg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:218	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:218:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:229	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:229:@done_on_match
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:238	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:238:@bufbeg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:240	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:240:@lastout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:247	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:247:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:255	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:255:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:267	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:267:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:282	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:282:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:290	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:290:@pending
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:294	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:294:@pending
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:298	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:298:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:302	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:302:@done_on_match
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:306	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:306:@out_invert
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:315	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:315:@out_before
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:316	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:316:@bufbeg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:320	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:320:@lastout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:352	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:352:@out_byte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:354	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:354:@totalcc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:355	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:355:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:372	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:372:@out_line
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:376	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:376:@lastnl
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:380	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:380:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:398	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:398:@totalnl
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:421	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:421:@suppress_errors
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:423	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:423:@filename
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:434	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:434:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:437	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:437:@bufbeg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:440	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:440:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:446	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:446:@pending
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:449	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:449:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:453	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:453:@done_on_match
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:456	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:456:@out_quiet
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:466	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:466:@filename
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:477	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:477:@count_matches
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:479	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:479:@out_file
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:482	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:482:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:485	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:485:@filename_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:489	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:489:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:492	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:492:@filename
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:493	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:493:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:495	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:495:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:498	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:498:@filename_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:502	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:502:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:505	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:505:@filename_mask
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:508	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:508:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:511	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:511:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:515	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:515:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:518	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:518:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:533	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:533:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:536	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:536:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:540	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:540:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:543	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:543:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:563	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:563:@list_files
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:568	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:568:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:571	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:571:@filename_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:575	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:575:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:578	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:578:@filename
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:579	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:579:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:581	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:581:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:584	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:584:@filename_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:588	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:588:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:591	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:591:@filename_mask
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:593	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:593:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:610	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:610:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:612	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:612:@bufoffset
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:613	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:613:@after_last_match
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:627	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:627:@filename
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:4	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:4:@excluded_directory_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:35	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:35:@suppress_errors
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:43	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:43:@included_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:44	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:44:@excluded_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:45	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:45:@excluded_directory_patterns
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:56	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:56:@suppress_errors
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:81	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:81:@no_filenames
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:84	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:84:@out_file
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:116	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:116:@no_filenames
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:117	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:117:@out_file
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:4	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:4:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:7	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:7:@buffer
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:12	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:12:@pagesize
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:13	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:13:@bufalloc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:48	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:48:@bufoffset
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:72	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:72:@pagesize
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:91	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:91:@buffer
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:94	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:94:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:95	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:95:@bufbeg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:98	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:98:@buffer
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:106	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:106:@bufalloc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:112	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:112:@pagesize
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:117	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:117:@bufdesc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:129	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:129:@bufoffset
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:19	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:19:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:26	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:26:@execute
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:33	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:33:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:43	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:43:@execute
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:66	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:66:@out_invert
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:72	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:72:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:76	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:76:@done_on_match
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:80	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:80:@exit_on_match
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:84	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:84:@bufoffset
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:85	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:85:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:100	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:100:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:105	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:105:@out_invert
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:116	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:116:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:2:@lastout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:5	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:5:@bufbeg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:8	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:8:@pending
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:14	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:14:@lastout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:17	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:17:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:26	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:26:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:31	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:31:@execute
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:37	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:37:@out_invert
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:41	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:41:@lastout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:46	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:46:@pending
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:4	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:4:@only_matching
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:9	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:9:@out_invert
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:12	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:12:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:18	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:18:@selected_line_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:19	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:19:@context_line_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:22	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:22:@selected_match_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:23	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:23:@context_match_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:29	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:29:@only_matching
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:61	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:61:@execute
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:85	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:85:@only_matching
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:87	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:87:@out_invert
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:95	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:95:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:105	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:105:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:109	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:109:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:115	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:115:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:121	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:121:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:123	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:123:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:129	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:129:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:132	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:132:@only_matching
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:134	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:134:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:148	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:148:@only_matching
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:171	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:171:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:199	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:199:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:201	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:201:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:208	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:208:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:212	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:212:@only_matching
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:220	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:220:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:223	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:223:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:236	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:236:@line_buffered
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:238	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:238:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:4	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:4:@out_file
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:7	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:7:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:10	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:10:@filename_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:14	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:14:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:17	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:17:@filename
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:18	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:18:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:20	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:20:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:23	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:23:@filename_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:27	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:27:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:30	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:30:@filename_mask
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:32	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:32:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:48	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:48:@out_line
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:50	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:50:@lastnl
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:58	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:58:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:77	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:77:@totalnl
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:105	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:105:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:108	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:108:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:112	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:112:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:117	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:117:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:134	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:134:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:137	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:137:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:141	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:141:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:144	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:144:@totalnl
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:145	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:145:@line_num_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:150	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:150:@out_byte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:152	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:152:@totalcc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:153	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:153:@bufbeg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:170	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:170:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:173	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:173:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:177	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:177:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:182	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:182:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:199	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:199:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:202	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:202:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:206	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:206:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:209	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:209:@byte_num_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:215	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:215:@align_tabs
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:217	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:217:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:220	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:220:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:223	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:223:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:227	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:227:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:232	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:232:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:249	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:249:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:252	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:252:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:256	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:256:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:25	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:25:@align_tabs
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:75	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:75:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:81	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:81:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:87	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:87:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:89	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:89:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:95	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:95:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:3	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:3:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:5	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:5:@out_quiet
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:7	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:7:@pending
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:12	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:12:@out_quiet
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:18	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:18:@lastout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:20	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:20:@bufbeg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:24	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:24:@out_before
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:44	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:44:@out_after
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:47	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:47:@prtext.used
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:51	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:51:@group_separator
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:55	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:55:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:58	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:58:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:62	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:62:@sgr_start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:64	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:64:@group_separator
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:67	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:67:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:69	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:69:@color_option
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:72	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:72:@sep_color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:76	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:76:@sgr_end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:79	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:79:@stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:120	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:120:@outleft
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:129	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:129:@out_quiet
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:146	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:146:@bufoffset
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:147	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:147:@buflim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:154	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:154:@out_quiet
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:159	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:159:@out_quiet
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:161	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:161:@out_after
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct:0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct:0:@selected_match_color
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn:1	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn:1:@dfawarn.mode
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:6	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:6:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:12	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:12:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:13	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:13:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:36	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:36:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:38	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:38:@pcount
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:50	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:50:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:53	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:53:@pcount
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:64	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:64:@pcount
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:72	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:72:@match_words
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:73	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:73:@match_lines
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:82	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:82:@match_lines
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:98	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:98:@match_lines
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:120	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:120:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:133	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:133:@kwset_exact_matches
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:146	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:146:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:161	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:161:@kwset
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:175	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:175:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:197	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:197:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:212	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:212:@kwset
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:226	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:226:@kwset
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:11	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:11:@eolbyte
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:17	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:17:@match_icase
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:53	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:53:@kwset
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:81	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:81:@kwset_exact_matches
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:97	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:97:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:101	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:101:@dfa
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:134	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:134:@pcount
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:154	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:154:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:159	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:159:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:166	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:166:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:177	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:177:@match_words
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:181	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:181:@match_lines
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:234	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:234:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:239	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:239:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:255	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:255:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:260	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:260:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:272	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:272:@patterns
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:299	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:299:@pcount
