</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:7	1	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:7:0
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:47	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:47:0
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:33	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:33:1
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:54	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:54:true
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:54	1	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:54:false
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:98	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:98:null
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:98	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:98:null
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:54	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:54:1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:78	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:78:0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:422	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:422:null
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:422	3	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:422:null
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:116	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:116:0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:233	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:233:null
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:270	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:270:0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:290	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:290:0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:304	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:304:null
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:304	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:304:null
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31:1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31:0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31:0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31	3	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31:1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31	4	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:31:0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:168	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:168:3
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:234	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:234:3
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:256	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:256:0
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:297	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:297:null
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:302	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:302:undef
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:474	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:474:1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:492	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:492:1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592	3	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592	4	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592	5	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592	6	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592	7	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592	8	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:592:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:31	2	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:31:null
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:216	1	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:216:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:216	2	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:216:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:216	3	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:216:-1
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:216	4	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:216:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:99	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:99:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:28	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:28:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:29	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:29:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:29	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:29:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:320	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:320:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:331	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:331:-48
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:344	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:344:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:355	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:355:-48
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:361	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:361:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:362	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:362:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:789	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:789:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:843	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:843:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:963	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:963:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1063	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1063:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1063	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1063:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1063	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1063:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1087	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1087:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1088	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1088:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1089	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1089:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1090	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1090:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1091	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1091:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1092	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1092:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1093	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1093:undef
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1166	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1166:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1295	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1295:getelementptr inbounds ([6 x i8]* @.str16, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1295	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1295:getelementptr inbounds ([6 x i8]* @.str16, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1307	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1307:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1308	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1308:getelementptr inbounds ([6 x i8]* @.str16, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1309	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1309:bitcast (<{ { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] }, { i8*, i32 (i32)*, i8, [7 x i8] } }>* @prednames to %struct.dfa_ctype*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1336	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1336:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1370	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1370:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1396	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1396:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1435	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1435:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1517	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1517:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1571	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1571:92
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1574	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1574:91
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1738	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1738:92
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1757	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1757:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1864	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1864:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2095	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2095:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:273
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	4	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	5	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	6	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	7	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	8	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	9	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	10	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	11	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136	12	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2136:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:91
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	5	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:46
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	6	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	7	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:40
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	8	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:10
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	9	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:124
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	10	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:124
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	11	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	12	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	13	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	14	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	15	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	16	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:43
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	17	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:43
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	18	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:43
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	19	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:42
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	20	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:42
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	21	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:63
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	22	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:63
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	23	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:63
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	24	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:66
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	25	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:66
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	26	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	27	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:98
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	28	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:62
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	29	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:62
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	30	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:60
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	31	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:60
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	32	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	33	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:39
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	34	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:96
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	35	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:96
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	38	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:36
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	39	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:36
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	40	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:36
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	41	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:94
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	42	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:94
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	43	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	44	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:41
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	45	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:36
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	46	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	47	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	48	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:123
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	49	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:92
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151	51	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2151:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:274
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	6	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:272
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	8	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:271
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	9	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:270
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	10	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:269
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	11	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:269
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	12	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:267
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	13	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	14	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	15	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	16	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	17	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	18	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:266
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	19	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:265
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	20	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:264
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	21	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:263
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	22	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:262
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	23	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:261
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	24	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:260
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	25	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:259
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	26	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:258
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	27	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:257
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	28	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:259
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	29	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:258
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	30	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182	31	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2182:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:90	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:90:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:120	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:120:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:172	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:172:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:213	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:213:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:266	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:266:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:350	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:350:false
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:350	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:350:false
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:377	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:377:true
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:425	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:425:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:449	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:449:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:490	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:490:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:520	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:520:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:521	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:521:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:537	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:537:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:552	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:552:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:604	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:604:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:605	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:605:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:618	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:618:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:17	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:17:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:18	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:18:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:32	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:32:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:33	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:33:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:19	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:19:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:53	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:53:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:61	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:61:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:118	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:118:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:133	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:133:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:148	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:148:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:197	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:197:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:197	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:197:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:25	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:25:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:26	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:26:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:27	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:27:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:44	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:44:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:45	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:45:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:46	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:46:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:50	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:50:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:72	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:72:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:99	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:99:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:115	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:115:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:123	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:123:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:167	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:167:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:214	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:214:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:31	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:31:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:85	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:85:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:88	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:88:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:152	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:152:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:167	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:167:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:296	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:296:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:296	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:296:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:308	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:308:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:566	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:566:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:583	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:583:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:583	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:583:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:627	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:627:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:663	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:663:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:690	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:690:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:691	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:691:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:692	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:692:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:715	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:715:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:728	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:728:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:729	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:729:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:763	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:763:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:782	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:782:false
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:782	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:782:true
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:783	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:783:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:783	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:783:256
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:812	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:812:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:813	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:813:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:824	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:824:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:826	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:826:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:838	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:838:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:856	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:856:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:871	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:871:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:921	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:921:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:932	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:932:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:942	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:942:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:942	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:942:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:942	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:942:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:956	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:956:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:973	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:973:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:988	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:988:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1046	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1046:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1047	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1047:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1060	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1060:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1067	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1067:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1078	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1078:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1079	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1079:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1092	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1092:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1092	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1092:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1111	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1111:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1116	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1116:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1153	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1153:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:21	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:21:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:50	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:50:false
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:50	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:50:true
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:51	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:51:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:51	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:51:256
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:65	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:65:2
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:144	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:144:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:146	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:146:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:146	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:146:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:150	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:150:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:152	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:152:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:423	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:423:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:423	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:423:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:15	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:15:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:16	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:16:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:69	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:69:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:74	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:74:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:34	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:34:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:35	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:35:zeroinitializer
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:36	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:36:zeroinitializer
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:51	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:51:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:52	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:52:zeroinitializer
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:53	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:53:zeroinitializer
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:87	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:87:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:97	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:97:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:97	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:97:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:97	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:97:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:99	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:99:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:202	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:202:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:226	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:226:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:244	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:244:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:259	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:259:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:13	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:13:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:37	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:37:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:66	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:66:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:66	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:66:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:66	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:66:4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:105	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:105:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:32	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:32:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:62	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:62:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:89	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:89:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:123	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:123:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:161	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:161:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:168	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:168:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:212	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:212:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:213	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:213:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:227	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:227:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:243	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:243:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:243	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:243:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:267	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:267:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:286	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:286:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:311	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:311:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:319	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:319:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:326	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:326:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:356	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:356:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:379	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:379:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:388	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:388:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:388	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:388:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:392	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:392:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:423	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:423:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:435	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:435:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:461	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:461:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:463	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:463:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:474	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:474:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:507	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:507:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:538	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:538:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:630	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:630:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	4	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	5	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	6	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	7	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	8	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	9	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	10	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	11	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	12	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	13	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	14	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	15	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	16	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	17	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	18	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	19	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	20	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674	21	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:674:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	4	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	5	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	6	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	7	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	8	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	9	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	10	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	11	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	12	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	13	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	14	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	15	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	16	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	17	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	18	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	19	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	20	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675	21	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:675:getelementptr inbounds ([1 x i8]* @dfamust.empty_string, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:701	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:701:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:710	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:710:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:722	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:722:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:761	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:761:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:20	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:20:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:45	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:45:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:69	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:69:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:12	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:12:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:37	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:37:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:57	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:57:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc:6	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc:6:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc:23	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc:23:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:13	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:13:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:29	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:29:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:52	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:52:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:125	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:125:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:133	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:133:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:151	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:151:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:151	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:151:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:151	4	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:151:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:151	5	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:151:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:35	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:35:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:80	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:80:4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:80	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:80:5
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:80	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:80:5
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:108	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:108:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:108	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:108:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:108	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:108:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:140	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:140:4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:140	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:140:5
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:140	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:140:5
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:213	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:213:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:247	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:247:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:272	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:272:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:311	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:311:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:334	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:334:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:347	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:347:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:347	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:347:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:347	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:347:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:347	4	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:347:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:23	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:23:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:35	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:35:true
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:35	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:35:false
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:35	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:35:false
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:37	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:37:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:106	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:106:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:140	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:140:null
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:151	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:151:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:171	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:171:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:191	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:191:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:206	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:206:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:31	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:31:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:39	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:39:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:94	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:94:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:343	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:343:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:350	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:350:1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:355	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:355:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:415	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:415:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:14	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:14:0
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:24	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:24:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:62	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:62:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:135	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:135:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:209	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:209:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:209	40	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:209:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:210	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:210:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:211	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:211:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:211	31	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:211:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:211	43	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:211:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:212	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:212:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:213	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:213:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:228	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:228:true
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:228	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:228:false
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:458	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:458:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:701	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:701:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:712	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:712:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:713	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:713:false
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:759	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:759:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:759	2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:759:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:775	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:775:getelementptr inbounds ([3 x i8]* @.str75, i64 0, i64 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:776	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:776:getelementptr inbounds ([12 x %struct.color_cap]* @color_dict, i64 0, i64 0, i32 0)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:888	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:888:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:914	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:914:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:39	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:39:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:40	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:40:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:88	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:88:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:88	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:88:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:121	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:121:32769
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:228	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:228:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:235	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:235:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:236	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:236:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:237	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:237:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:297	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:297:false
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:332	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:332:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:384	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:384:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:397	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:397:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:476	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:476:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:476	2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:476:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:476	3	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:476:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:476	4	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:476:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	3	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	4	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	5	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	6	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	7	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	8	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	9	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639	10	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:639:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:73	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:73:false
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:95	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:95:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:96	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:96:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:121	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:121:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:122	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:122:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:131	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:131:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:131	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:131:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:131	2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:131:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:131	4	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:131:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:125	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:125:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:11	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:11:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:27	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:27:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:28	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:28:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:60	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:60:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:108	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:108:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:151	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:151:null
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:175	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:175:false
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:187	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:187:false
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:47	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:47:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:47	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:47:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:47	2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:47:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:47	3	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:47:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:63	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:63:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:76	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:76:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:149	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:149:1
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:44	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:44:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:59	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:59:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:28	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:28:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:118	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:118:0
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:144	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:144:0
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:33	1	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:33:null
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:34	1	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:34:0
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:114	1	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:114:null
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:31	2	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:31:null
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:151	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:151:0
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:152	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:152:0
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:323	1	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:323:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:323	2	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:323:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:323	3	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:323:-1
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:323	4	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:323:-1
