</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:0	8
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:2	8
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:4	4
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:0	8
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:0	16
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:1	16
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:0	16
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:1	8
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:2	16
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:0	8
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:0	8
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:1	8
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:2	8
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:3	8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:0	1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:3	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:4	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:5	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:6	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:7	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:8	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:9	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:10	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:11	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:12	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:13	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:14	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:15	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:16	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:17	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:18	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:19	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:20	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:21	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:0	8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:1	8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:2	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:3	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:4	8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:0	8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:0	4
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:1	8
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:0	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:1	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:0	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:1	16
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:2	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:0	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:1	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:2	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:3	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:4	16
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:5	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:0	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:0	4
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:1	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:0	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:0	8
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:0	16
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:0	8
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:1	8
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:0	8
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:1	8
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:2	4
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:3	8
