</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:1	%struct.__mbstate_t*
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:3	%struct.__mbstate_t*
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:1	%struct.__mbstate_t*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:2	%struct.kwset.0*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:6	%struct.obstack*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:9	i32*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:15	i8**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:18	i8**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:33	i8**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:45	i32*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:55	%struct._obstack_chunk**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:69	%struct.trie*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:71	%struct.trie**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:81	i32*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:85	i32*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:89	i32*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:92	i8**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:95	i8**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree:6	i8*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:5	i8*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:8	i8*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:48	%struct.tree*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:126	%struct.tree*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:178	%struct.trie*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:180	%struct.trie**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:186	i8*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:198	i32*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:201	%struct.tree**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:204	%struct.trie**
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:212	i32*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:215	i32*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:3	i8*
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:282	i8*
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:4	%struct.__mbstate_t.6*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:742	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:783	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:815	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:820	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:837	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:871	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:876	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:889	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:891	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:893	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:895	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:897	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:899	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:901	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:903	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:905	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:907	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:909	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:911	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:938	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:942	%struct.mb_char_classes*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:960	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1333	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1349	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1353	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1393	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1409	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1413	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1432	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1448	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1452	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1746	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1753	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1768	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1772	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1787	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1791	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1985	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:1989	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2018	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2022	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2107	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2112	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex:2171	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:19	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:27	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:52	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:58	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:64	%struct.position_set*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:72	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:74	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:75	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:151	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:155	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:176	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:177	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:245	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:249	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:270	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:271	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:328	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:329	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:409	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:453	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:454	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:473	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:477	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:494	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:495	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:523	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:575	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:576	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:624	%struct.dfa_state*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:634	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:55	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:56	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:77	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:78	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:88	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:89	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:124	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:125	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:142	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:143	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:42	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:75	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:76	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:169	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:170	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:138	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:142	%struct.dfa_state*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:155	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:171	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:172	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:0	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:18	%struct.position_set*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:22	[8 x i32]*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:67	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:81	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:82	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:118	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:131	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:192	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:193	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:239	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:242	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:246	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:249	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:261	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:264	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:269	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:272	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:280	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:283	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:287	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:290	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:529	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:532	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:538	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:559	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:561	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:572	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:573	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:574	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:575	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:589	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:590	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:634	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:641	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:646	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:649	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:668	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:719	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:720	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:752	i16*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:753	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:765	<4 x i16>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:777	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:844	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:890	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:891	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:961	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1007	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1008	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1156	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:86	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:90	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:96	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:103	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:110	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:137	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:227	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:257	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:348	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:400	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:38	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:42	<4 x i32>*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:84	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:158	%struct.position*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:232	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:278	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:279	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:342	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:345	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:17	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:22	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:93	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:119	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:121	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:124	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:127	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:132	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:135	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:140	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:143	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:148	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit:1	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit:6	[8 x i32]*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit:12	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit:24	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit:30	%struct.mb_char_classes*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:15	%struct.must*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:30	%struct.must*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:34	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:257	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:289	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:372	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:402	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:436	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:451	%struct.must*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:454	i8***
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:476	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:680	%struct.dfamust*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:682	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:688	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:694	%struct.dfamust**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:723	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:3	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:7	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:24	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:29	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:37	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:49	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:57	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:73	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:78	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:88	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:91	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:95	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:99	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:113	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:3	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:17	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:21	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:25	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:29	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:49	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:69	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:77	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaalloc:1	%struct.dfa*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:134	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:139	i8**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:13	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:23	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:111	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:112	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:177	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:227	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:228	i64*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:271	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:16	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:18	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:21	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:26	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:31	i32**
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:35	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:40	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:44	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:49	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:19	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:23	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:53	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:57	i32*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:14	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:16	%struct.__mbstate_t.8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:75	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:97	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:7	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:18	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:36	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:40	[8 x i32]*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:59	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:60	i8*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:107	i8**
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:125	i8**
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:203	i32*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:204	i8*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:205	i8*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:206	i8*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:207	i8*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:781	%struct.color_cap*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:787	i8**
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:801	%struct.color_cap*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:76	i8*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:44	i8*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:48	<16 x i8>*
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:52	<16 x i8>*
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:37	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:42	%struct.patterns*
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:55	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:126	i8*
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:180	i8*
