</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit	@kwsinit
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.declare	@llvm.dbg.declare
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_get_mb_cur_max	@__ctype_get_mb_cur_max
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsalloc	@kwsalloc
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xalloc_die	@xalloc_die
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower	@mbtolower
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xrealloc	@xrealloc
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__assert_fail	@__assert_fail
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbrtowc	@mbrtowc
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:wcrtomb	@wcrtomb
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:towlower	@towlower
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	@is_mb_middle
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_tolower_loc	@__ctype_tolower_loc
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.value	@llvm.dbg.value
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc	@kwsalloc
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.declare	@llvm.dbg.declare
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:xmalloc	@xmalloc
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:_obstack_begin	@_obstack_begin
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:free	@free
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:_obstack_newchunk	@_obstack_newchunk
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree	@kwsfree
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	@kwsincr
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.start	@llvm.lifetime.start
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:dcgettext	@dcgettext
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:obstack_free	@obstack_free
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:abort	@abort
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.end	@llvm.lifetime.end
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep	@kwsprep
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memset.p0i8.i64	@llvm.memset.p0i8.i64
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue	@enqueue
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	@treedelta
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	@treefails
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	@hasevery
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext	@treenext
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memcpy.p0i8.p0i8.i64	@llvm.memcpy.p0i8.p0i8.i64
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	@kwsexec
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:memchr	@memchr
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.value	@llvm.dbg.value
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile	@Gcompile
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:EGexecute	@EGexecute
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile	@Ecompile
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile	@Acompile
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Fcompile	@Fcompile
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Fexecute	@Fexecute
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Pcompile	@Pcompile
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Pexecute	@Pexecute
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:GEAcompile	@GEAcompile
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:llvm.dbg.value	@llvm.dbg.value
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:Fcompile	@Fcompile
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:Fexecute	@Fexecute
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile	@Ecompile
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:EGexecute	@EGexecute
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:GEAcompile	@GEAcompile
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:llvm.dbg.value	@llvm.dbg.value
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile	@Fcompile
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.declare	@llvm.dbg.declare
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsinit	@kwsinit
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_get_mb_cur_max	@__ctype_get_mb_cur_max
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbtolower	@mbtolower
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsincr	@kwsincr
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:error	@error
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsprep	@kwsprep
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	@Fexecute
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsexec	@kwsexec
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:is_mb_middle	@is_mb_middle
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_b_loc	@__ctype_b_loc
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:memchr	@memchr
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbrtowc	@mbrtowc
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.value	@llvm.dbg.value
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	@dfasyntax
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.declare	@llvm.dbg.declare
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	@dfaparse
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:hard_locale	@hard_locale
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_get_mb_cur_max	@__ctype_get_mb_cur_max
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memset.p0i8.i64	@llvm.memset.p0i8.i64
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaerror	@dfaerror
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dcgettext	@dcgettext
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex	@lex
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze	@dfaanalyze
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xmalloc	@xmalloc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xcalloc	@xcalloc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	@merge
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xrealloc	@xrealloc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memcpy.p0i8.p0i8.i64	@llvm.memcpy.p0i8.p0i8.i64
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure	@epsclosure
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	@state_index
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free	@free
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	@dfastate
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_b_loc	@__ctype_b_loc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	@dfaexec
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf	@prepare_wc_buf
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	@transit_state
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state	@build_state
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit	@dfainit
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	@dfacomp
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree	@dfafree
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata	@free_mbdata
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaalloc	@dfaalloc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts	@dfamusts
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:malloc	@malloc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__assert_fail	@__assert_fail
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcmp	@strcmp
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strlen	@strlen
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc	@icatalloc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	@enlist
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcpy	@strcpy
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc	@realloc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncmp	@strncmp
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strchr	@strchr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:abort	@abort
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nl_langinfo	@nl_langinfo
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	@check_matching_with_multibyte_ops
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	@transit_state_consume_1char
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalnum	@iswalnum
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary	@realloc_trans_if_necessary
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.start	@llvm.lifetime.start
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswctype	@iswctype
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncpy	@strncpy
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcoll	@strcoll
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcscoll	@wcscoll
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.end	@llvm.lifetime.end
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:mbrtowc	@mbrtowc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb	@addtok_mb
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure	@closure
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks	@nsubtoks
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towlower	@towlower
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index	@charclass_index
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:memcmp	@memcmp
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcrtomb	@wcrtomb
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctob	@wctob
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold	@setbit_case_fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswupper	@iswupper
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswlower	@iswlower
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towupper	@towupper
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_toupper_loc	@__ctype_toupper_loc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_tolower_loc	@__ctype_tolower_loc
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctype	@wctype
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalpha	@iswalpha
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfawarn	@dfawarn
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalpha	@isalpha
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isupper	@isupper
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:islower	@islower
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isdigit	@isdigit
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isxdigit	@isxdigit
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isspace	@isspace
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:ispunct	@ispunct
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalnum	@isalnum
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isprint	@isprint
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isgraph	@isgraph
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iscntrl	@iscntrl
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isblank	@isblank
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.value	@llvm.dbg.value
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage	@usage
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.declare	@llvm.dbg.declare
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fprintf	@fprintf
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:dcgettext	@dcgettext
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:printf	@printf
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fputs_unlocked	@fputs_unlocked
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:exit	@exit
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	@main
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:set_program_name	@set_program_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setlocale	@setlocale
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:bindtextdomain	@bindtextdomain
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:textdomain	@textdomain
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:atexit	@atexit
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:close_stdout	@close_stdout
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getenv	@getenv
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher	@setmatcher
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcmp	@strcmp
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:error	@error
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xargmatch_internal	@__xargmatch_internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strlen	@strlen
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xrealloc	@xrealloc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcpy	@strcpy
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fopen	@fopen
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__errno_location	@__errno_location
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fread_unlocked	@fread_unlocked
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fclose	@fclose
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xstrtoumax	@xstrtoumax
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcasecmp	@strcasecmp
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isatty	@isatty
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:new_exclude	@new_exclude
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:add_exclude	@add_exclude
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:add_exclude_file	@add_exclude_file
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:version_etc	@version_etc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:proper_name	@proper_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xmalloc	@xmalloc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:free	@free
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isdir	@isdir
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:excluded_file_name	@excluded_file_name
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile	@grepfile
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:open	@open
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir	@grepdir
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:lseek	@lseek
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:close	@close
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__overflow	@__overflow
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf	@fillbuf
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:memchr	@memchr
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf	@grepbuf
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending	@prpending
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	@prline
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	@print_line_head
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fwrite_unlocked	@fwrite_unlocked
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fflush_unlocked	@fflush_unlocked
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	@print_offset
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.start	@llvm.lifetime.start
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.end	@llvm.lifetime.end
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	@prtext
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__ctype_get_mb_cur_max	@__ctype_get_mb_cur_max
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xalloc_die	@xalloc_die
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.memmove.p0i8.p0i8.i64	@llvm.memmove.p0i8.p0i8.i64
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:read	@read
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getpagesize	@getpagesize
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:abort	@abort
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:savedir	@savedir
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xstat	@__xstat
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct	@color_cap_mt_fct
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_rv_fct	@color_cap_rv_fct
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_ne_fct	@color_cap_ne_fct
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getopt_long	@getopt_long
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.value	@llvm.dbg.value
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.uadd.with.overflow.i64	@llvm.uadd.with.overflow.i64
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror	@dfaerror
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.declare	@llvm.dbg.declare
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:error	@error
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:abort	@abort
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn	@dfawarn
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:getenv	@getenv
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	@GEAcompile
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_set_syntax	@re_set_syntax
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfasyntax	@dfasyntax
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:memchr	@memchr
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:realloc	@realloc
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__errno_location	@__errno_location
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dcgettext	@dcgettext
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memcpy.p0i8.p0i8.i64	@llvm.memcpy.p0i8.p0i8.i64
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_compile_pattern	@re_compile_pattern
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:xmalloc	@xmalloc
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strcpy	@strcpy
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strlen	@strlen
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaalloc	@dfaalloc
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfacomp	@dfacomp
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:free	@free
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	@EGexecute
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_get_mb_cur_max	@__ctype_get_mb_cur_max
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:mbtolower	@mbtolower
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsexec	@kwsexec
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:is_mb_middle	@is_mb_middle
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaexec	@dfaexec
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_search	@re_search
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_b_loc	@__ctype_b_loc
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_match	@re_match
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfamusts	@dfamusts
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsinit	@kwsinit
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsprep	@kwsprep
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsincr	@kwsincr
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.value	@llvm.dbg.value
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.start	@llvm.lifetime.start
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.end	@llvm.lifetime.end
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memset.p0i8.i64	@llvm.memset.p0i8.i64
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile	@Pcompile
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:error	@error
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:dcgettext	@dcgettext
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	@Pexecute
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:abort	@abort
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:llvm.dbg.value	@llvm.dbg.value
