</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.declare	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.declare	readnone
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_get_mb_cur_max	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xalloc_die	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__assert_fail	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__assert_fail	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbrtowc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:wcrtomb	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:towlower	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_tolower_loc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_tolower_loc	readnone
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.value	readnone
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.declare	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.declare	readnone
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:free	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.start	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:dcgettext	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:abort	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:abort	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.end	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memset.p0i8.i64	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	readonly
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memcpy.p0i8.p0i8.i64	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:memchr	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:memchr	readonly
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.value	readnone
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:llvm.dbg.value	readnone
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:llvm.dbg.value	readnone
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.declare	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.declare	readnone
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_get_mb_cur_max	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_b_loc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_b_loc	readnone
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:memchr	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:memchr	readonly
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbrtowc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.value	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.declare	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.declare	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_get_mb_cur_max	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memset.p0i8.i64	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaerror	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dcgettext	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memcpy.p0i8.p0i8.i64	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_b_loc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_b_loc	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaalloc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaalloc	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:malloc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__assert_fail	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__assert_fail	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcmp	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcmp	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strlen	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strlen	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcpy	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncmp	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncmp	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strchr	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strchr	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:abort	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:abort	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nl_langinfo	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalnum	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.start	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswctype	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncpy	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcoll	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcoll	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcscoll	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.end	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:mbrtowc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towlower	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:memcmp	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:memcmp	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcrtomb	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctob	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswupper	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswlower	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towupper	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_toupper_loc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_toupper_loc	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_tolower_loc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_tolower_loc	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctype	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalpha	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalpha	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isupper	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:islower	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isdigit	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isxdigit	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isspace	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:ispunct	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalnum	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isprint	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isgraph	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iscntrl	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isblank	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.value	readnone
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.declare	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.declare	readnone
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fprintf	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:dcgettext	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:printf	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:exit	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:exit	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setlocale	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:bindtextdomain	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:textdomain	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:atexit	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getenv	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getenv	readonly
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcmp	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcmp	readonly
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strlen	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strlen	readonly
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcpy	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fopen	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__errno_location	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__errno_location	readnone
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fclose	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcasecmp	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcasecmp	readonly
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isatty	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:free	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:lseek	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:memchr	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:memchr	readonly
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.start	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.end	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__ctype_get_mb_cur_max	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xalloc_die	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.memmove.p0i8.p0i8.i64	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getpagesize	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getpagesize	readnone
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:abort	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:abort	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xstat	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_rv_fct	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_rv_fct	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_ne_fct	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_ne_fct	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getopt_long	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.value	readnone
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.uadd.with.overflow.i64	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.uadd.with.overflow.i64	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.declare	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.declare	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:abort	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:abort	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:getenv	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:getenv	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:memchr	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:memchr	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:realloc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__errno_location	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__errno_location	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dcgettext	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memcpy.p0i8.p0i8.i64	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strcpy	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strlen	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strlen	readonly
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:free	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_get_mb_cur_max	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_b_loc	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_b_loc	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.value	readnone
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.start	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.end	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memset.p0i8.i64	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:dcgettext	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	uwtable
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:abort	noreturn
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:abort	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:llvm.dbg.value	nounwind
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:llvm.dbg.value	readnone
