</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.declare	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_get_mb_cur_max	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xalloc_die	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xrealloc	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__assert_fail	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbrtowc	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:wcrtomb	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:towlower	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_tolower_loc	external
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.value	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.declare	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:xmalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:_obstack_begin	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:free	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:_obstack_newchunk	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.start	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:dcgettext	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:obstack_free	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:abort	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.end	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memset.p0i8.i64	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue	internal
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	internal
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	internal
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	internal
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext	internal
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memcpy.p0i8.p0i8.i64	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:memchr	external
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.value	external
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile	internal
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:EGexecute	external
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile	internal
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile	internal
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Fcompile	external
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Fexecute	external
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Pcompile	external
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Pexecute	external
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:GEAcompile	external
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:llvm.dbg.value	external
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:Fcompile	external
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:Fexecute	external
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile	internal
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:EGexecute	external
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:GEAcompile	external
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:llvm.dbg.value	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.declare	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsinit	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_get_mb_cur_max	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbtolower	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsincr	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:error	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsprep	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsexec	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:is_mb_middle	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_b_loc	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:memchr	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbrtowc	external
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.value	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.declare	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:hard_locale	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_get_mb_cur_max	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memset.p0i8.i64	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaerror	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dcgettext	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xmalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xcalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xrealloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memcpy.p0i8.p0i8.i64	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_b_loc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:malloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__assert_fail	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcmp	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strlen	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcpy	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncmp	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strchr	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:abort	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nl_langinfo	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalnum	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.start	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswctype	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncpy	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcoll	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcscoll	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.end	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:mbrtowc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towlower	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:memcmp	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcrtomb	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctob	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold	internal
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswupper	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswlower	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towupper	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_toupper_loc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_tolower_loc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctype	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalpha	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfawarn	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalpha	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isupper	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:islower	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isdigit	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isxdigit	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isspace	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:ispunct	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalnum	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isprint	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isgraph	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iscntrl	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isblank	external
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.value	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.declare	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fprintf	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:dcgettext	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:printf	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fputs_unlocked	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:exit	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:set_program_name	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setlocale	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:bindtextdomain	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:textdomain	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:atexit	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:close_stdout	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getenv	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcmp	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:error	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xargmatch_internal	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strlen	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xrealloc	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcpy	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fopen	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__errno_location	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fread_unlocked	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fclose	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xstrtoumax	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcasecmp	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isatty	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:new_exclude	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:add_exclude	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:add_exclude_file	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:version_etc	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:proper_name	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xmalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:free	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isdir	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:excluded_file_name	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:open	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:lseek	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:close	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__overflow	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:memchr	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fwrite_unlocked	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fflush_unlocked	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.start	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.end	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__ctype_get_mb_cur_max	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xalloc_die	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.memmove.p0i8.p0i8.i64	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:read	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getpagesize	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:abort	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:savedir	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xstat	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_rv_fct	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_ne_fct	internal
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getopt_long	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.value	external
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.uadd.with.overflow.i64	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.declare	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:error	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:abort	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:getenv	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_set_syntax	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfasyntax	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:memchr	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:realloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__errno_location	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dcgettext	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memcpy.p0i8.p0i8.i64	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_compile_pattern	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:xmalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strcpy	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strlen	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaalloc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfacomp	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:free	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_get_mb_cur_max	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:mbtolower	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsexec	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:is_mb_middle	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaexec	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_search	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_b_loc	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_match	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfamusts	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsinit	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsprep	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsincr	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.value	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.start	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.end	external
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memset.p0i8.i64	external
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile	external
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:error	external
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:dcgettext	external
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	external
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:abort	external
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:llvm.dbg.value	external
