</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit	void (%struct.kwset**)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.declare	void (metadata, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_get_mb_cur_max	i64 ()
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsalloc	%struct.kwset* (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xalloc_die	void ()
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower	i8* (i8*, i64*)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xrealloc	i8* (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__assert_fail	void (i8*, i8*, i32, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbrtowc	i64 (i32*, i8*, i64, %struct.__mbstate_t*)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:wcrtomb	i64 (i8*, i32, %struct.__mbstate_t*)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:towlower	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	i1 (i8**, i8*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_tolower_loc	i32** ()
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.value	void (metadata, i64, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc	%struct.kwset.0* (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.declare	void (metadata, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:xmalloc	i8* (i64)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:_obstack_begin	i32 (%struct.obstack*, i32, i32, i8* (i64)*, void (i8*)*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:free	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:_obstack_newchunk	void (%struct.obstack*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree	void (%struct.kwset.0*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	i8* (%struct.kwset.0*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.start	void (i64, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:dcgettext	i8* (i8*, i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:obstack_free	void (%struct.obstack*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:abort	void ()
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.end	void (i64, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep	i8* (%struct.kwset.0*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memset.p0i8.i64	void (i8*, i8, i64, i32, i1)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue	void (%struct.tree*, %struct.trie**)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	void (%struct.tree*, i32, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	void (%struct.tree*, %struct.trie*, %struct.trie*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	i32 (%struct.tree*, %struct.tree*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext	void (%struct.tree*, %struct.trie**)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memcpy.p0i8.p0i8.i64	void (i8*, i8*, i64, i32, i1)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	i64 (%struct.kwset.0*, i8*, i64, %struct.kwsmatch*)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:memchr	i8* (i8*, i32, i64)
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.value	void (metadata, i64, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:EGexecute	i64 (i8*, i64, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Fcompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Fexecute	i64 (i8*, i64, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Pcompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Pexecute	i64 (i8*, i64, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:GEAcompile	void (i8*, i64, i64)
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:llvm.dbg.value	void (metadata, i64, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:Fcompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:Fexecute	i64 (i8*, i64, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:EGexecute	i64 (i8*, i64, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:GEAcompile	void (i8*, i64, i64)
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:llvm.dbg.value	void (metadata, i64, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.declare	void (metadata, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsinit	void (%struct.kwset.4**)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_get_mb_cur_max	i64 ()
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbtolower	i8* (i8*, i64*)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsincr	i8* (%struct.kwset.4*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:error	void (i32, i32, i8*, ...)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsprep	i8* (%struct.kwset.4*)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	i64 (i8*, i64, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsexec	i64 (%struct.kwset.4*, i8*, i64, %struct.kwsmatch.5*)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:is_mb_middle	i1 (i8**, i8*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_b_loc	i16** ()
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:memchr	i8* (i8*, i32, i64)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbrtowc	i64 (i32*, i8*, i64, %struct.__mbstate_t.6*)
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.value	void (metadata, i64, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	void (i64, i32, i8)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.declare	void (metadata, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	void (i8*, i64, %struct.dfa*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:hard_locale	i1 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_get_mb_cur_max	i64 ()
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memset.p0i8.i64	void (i8*, i8, i64, i32, i1)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaerror	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dcgettext	i8* (i8*, i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex	i32 ()
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze	void (%struct.dfa*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xmalloc	i8* (i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xcalloc	i8* (i64, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	void (%struct.position_set*, %struct.position_set*, %struct.position_set*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xrealloc	i8* (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memcpy.p0i8.p0i8.i64	void (i8*, i8*, i64, i32, i1)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure	void (%struct.position_set*, %struct.dfa*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	i32 (%struct.dfa*, %struct.position_set*, i32, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	void (i32, %struct.dfa*, i32*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_b_loc	i16** ()
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	i8* (%struct.dfa*, i8*, i8*, i32, i32*, i32*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf	void (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	i32 (%struct.dfa*, i32, i8**)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state	void (i32, %struct.dfa*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit	void (%struct.dfa*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	void (i8*, i64, %struct.dfa*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree	void (%struct.dfa*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata	void (%struct.dfa*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaalloc	%struct.dfa* ()
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts	%struct.dfamust* (%struct.dfa*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:malloc	i8* (i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__assert_fail	void (i8*, i8*, i32, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcmp	i32 (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strlen	i64 (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc	i8* (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	i8** (i8**, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcpy	i8* (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc	i8* (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncmp	i32 (i8*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strchr	i8* (i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:abort	void ()
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nl_langinfo	i8* (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	i32* (%struct.dfa*, i32, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	void (%struct.dfa*, i32, i8**, i32*, i32*, %struct.position_set*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalnum	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary	void (%struct.dfa*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.start	void (i64, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswctype	i32 (i32, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncpy	i8* (i8*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcoll	i32 (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcscoll	i32 (i32*, i32*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.end	void (i64, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:mbrtowc	i64 (i32*, i8*, i64, %struct.__mbstate_t.8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb	void (i32, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure	void ()
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towlower	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index	i32 (i32*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:memcmp	i32 (i8*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcrtomb	i64 (i8*, i32, %struct.__mbstate_t.8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctob	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold	void (i32, i32*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswupper	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswlower	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towupper	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_toupper_loc	i32** ()
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_tolower_loc	i32** ()
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctype	i64 (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalpha	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfawarn	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalpha	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isupper	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:islower	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isdigit	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isxdigit	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isspace	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:ispunct	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalnum	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isprint	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isgraph	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iscntrl	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isblank	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.value	void (metadata, i64, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage	void (i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.declare	void (metadata, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fprintf	i32 (%struct._IO_FILE*, i8*, ...)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:dcgettext	i8* (i8*, i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:printf	i32 (i8*, ...)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fputs_unlocked	i32 (i8*, %struct._IO_FILE*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:exit	void (i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	i32 (i32, i8**)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:set_program_name	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setlocale	i8* (i32, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:bindtextdomain	i8* (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:textdomain	i8* (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:atexit	i32 (void ()*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:close_stdout	void ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getenv	i8* (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcmp	i32 (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:error	void (i32, i32, i8*, ...)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xargmatch_internal	i64 (i8*, i8*, i8**, i8*, i64, void ()*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strlen	i64 (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xrealloc	i8* (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcpy	i8* (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fopen	%struct._IO_FILE* (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__errno_location	i32* ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fread_unlocked	i64 (i8*, i64, i64, %struct._IO_FILE*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fclose	i32 (%struct._IO_FILE*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xstrtoumax	i32 (i8*, i8**, i32, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcasecmp	i32 (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isatty	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:new_exclude	%struct.exclude* ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:add_exclude	void (%struct.exclude*, i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:add_exclude_file	i32 (void (%struct.exclude*, i8*, i32)*, %struct.exclude*, i8*, i32, i8)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:version_etc	void (%struct._IO_FILE*, i8*, i8*, i8*, ...)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:proper_name	i8* (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xmalloc	i8* (i64)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:free	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isdir	i32 (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:excluded_file_name	i1 (%struct.exclude*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile	i32 (i8*, %struct.stats*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:open	i32 (i8*, i32, ...)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir	i32 (i8*, %struct.stats*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:lseek	i64 (i32, i64, i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:close	i32 (i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__overflow	i32 (%struct._IO_FILE*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf	i32 (i64, %struct.stats*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:memchr	i8* (i8*, i32, i64)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf	i32 (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	void (i8*, i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	void (i8*, i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fwrite_unlocked	i64 (i8*, i64, i64, %struct._IO_FILE*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fflush_unlocked	i32 (%struct._IO_FILE*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	void (i64, i32, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.start	void (i64, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.end	void (i64, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	void (i8*, i8*, i32*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__ctype_get_mb_cur_max	i64 ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xalloc_die	void ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.memmove.p0i8.p0i8.i64	void (i8*, i8*, i64, i32, i1)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:read	i64 (i32, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getpagesize	i32 ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:abort	void ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:savedir	i8* (i8*, i64, %struct.exclude*, %struct.exclude*, %struct.exclude*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xstat	i32 (i32, i8*, %struct.stat*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct	i8* ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_rv_fct	i8* ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_ne_fct	i8* ()
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getopt_long	i32 (i32, i8**, i8*, %struct.option*, i32*)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.value	void (metadata, i64, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.uadd.with.overflow.i64	{ i64, i1 } (i64, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.declare	void (metadata, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:error	void (i32, i32, i8*, ...)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:abort	void ()
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:getenv	i8* (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	void (i8*, i64, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_set_syntax	i64 (i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfasyntax	void (i64, i32, i8)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:memchr	i8* (i8*, i32, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:realloc	i8* (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__errno_location	i32* ()
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dcgettext	i8* (i8*, i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memcpy.p0i8.p0i8.i64	void (i8*, i8*, i64, i32, i1)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_compile_pattern	i8* (i8*, i64, %struct.re_pattern_buffer*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:xmalloc	i8* (i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strcpy	i8* (i8*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strlen	i64 (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaalloc	%struct.dfa.11* ()
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfacomp	void (i8*, i64, %struct.dfa.11*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:free	void (i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	i64 (i8*, i64, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_get_mb_cur_max	i64 ()
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:mbtolower	i8* (i8*, i64*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsexec	i64 (%struct.kwset.12*, i8*, i64, %struct.kwsmatch.14*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:is_mb_middle	i1 (i8**, i8*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaexec	i8* (%struct.dfa.11*, i8*, i8*, i32, i32*, i32*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_search	i32 (%struct.re_pattern_buffer*, i8*, i32, i32, i32, %struct.re_registers*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_b_loc	i16** ()
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_match	i32 (%struct.re_pattern_buffer*, i8*, i32, i32, %struct.re_registers*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfamusts	%struct.dfamust.13* (%struct.dfa.11*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsinit	void (%struct.kwset.12**)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsprep	i8* (%struct.kwset.12*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsincr	i8* (%struct.kwset.12*, i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.value	void (metadata, i64, metadata)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.start	void (i64, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.end	void (i64, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memset.p0i8.i64	void (i8*, i8, i64, i32, i1)
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile	void (i8*, i64)
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:error	void (i32, i32, i8*, ...)
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:dcgettext	i8* (i8*, i8*, i32)
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	i64 (i8*, i64, i64*, i8*)
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:abort	void ()
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:llvm.dbg.value	void (metadata, i64, metadata)
