</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	zeroext
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:xmalloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:is_mb_middle	zeroext
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:hard_locale	zeroext
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xmalloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xcalloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaalloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:malloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	noalias
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fopen	noalias
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xmalloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:excluded_file_name	zeroext
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct	noalias
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_rv_fct	noalias
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_ne_fct	noalias
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:realloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:xmalloc	noalias
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:is_mb_middle	zeroext
