</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:%kwset
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:%beg
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower	1	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower:%n
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	0	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:%good
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	1	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:%buf
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	2	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:%end
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	3	</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle:%match_len
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc:%trans
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree:%kws
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%kws
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%text
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr:%len
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep:%kws
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue:%tree
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue:%last
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta:%tree
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta:%depth
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta:%delta
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails:%tree
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails:%fail
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails:%recourse
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:%a
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery:%b
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext:%tree
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext:%next
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	0	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%kws
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	1	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%text
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	2	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%size
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	3	</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec:%kwsmatch
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile	0	</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile:%pattern
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile	1	</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile:%size
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile	0	</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile:%pattern
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile	1	</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile:%size
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile	0	</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile:%pattern
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile	1	</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile:%size
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile	0	</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile:%pattern
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile	1	</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile:%size
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:%pattern
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile	1	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:%size
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	0	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%buf
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	1	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%size
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	2	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%match_size
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	3	</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute:%start_ptr
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax:%bits
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax:%fold
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax:%eol
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:%len
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:%searchflag
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%s1
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%s2
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:%m
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%newline
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index:%letter
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:%trans
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%end
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%newline
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	4	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%count
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	5	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec:%backref
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%begin
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:%end
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state:%pp
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%len
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:%searchflag
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc:%old
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc:%new
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%cpp
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%new
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist:%len
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops:%idx
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	2	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%pp
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	3	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%match_lens
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	4	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%mbclen
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	5	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:%pps
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:%d
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:%new_state
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:%t
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:%mbprop
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks:%tindex
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index:%s
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold	0	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%b
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold	1	</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:%c
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage:%status
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%argc
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main:%argv
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:%m
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%file
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile:%stats
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:%dir
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir:%stats
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%save
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf:%stats
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:%beg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf:%lim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:%lim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%beg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%lim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:%sep
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:%beg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:%lim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:%sep
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:%pos
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:%min_width
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:%color
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	0	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:%beg
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	1	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:%lim
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	2	</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:%nlinesp
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror:%mesg
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn:%mesg
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:%pattern
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	1	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:%size
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	2	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:%syntax_bits
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	0	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%buf
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	1	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%size
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	2	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%match_size
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	3	</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute:%start_ptr
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile	0	</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile:%pattern
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile	1	</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile:%size
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	0	</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute:%buf
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	1	</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute:%size
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	2	</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute:%match_size
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	3	</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute:%start_ptr
