</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.declare	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_get_mb_cur_max	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xalloc_die	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbtolower	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:xrealloc	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__assert_fail	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:mbrtowc	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:wcrtomb	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:towlower	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:is_mb_middle	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:__ctype_tolower_loc	default
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:llvm.dbg.value	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.declare	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:xmalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:_obstack_begin	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:free	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:_obstack_newchunk	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsincr	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.start	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:dcgettext	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:obstack_free	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:abort	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.lifetime.end	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsprep	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memset.p0i8.i64	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:hasevery	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.memcpy.p0i8.p0i8.i64	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsexec	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:memchr	default
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:llvm.dbg.value	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:EGexecute	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Fcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Fexecute	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Pcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Pexecute	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:GEAcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:llvm.dbg.value	default
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:Fcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:Fexecute	default
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile	default
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:EGexecute	default
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:GEAcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:llvm.dbg.value	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.declare	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsinit	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_get_mb_cur_max	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbtolower	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsincr	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:error	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsprep	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fexecute	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:kwsexec	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:is_mb_middle	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:__ctype_b_loc	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:memchr	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:mbrtowc	default
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:llvm.dbg.value	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.declare	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:hard_locale	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_get_mb_cur_max	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memset.p0i8.i64	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaerror	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dcgettext	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:lex	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xmalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xcalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:xrealloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.memcpy.p0i8.p0i8.i64	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:state_index	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_b_loc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaexec	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfamusts	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:malloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__assert_fail	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcmp	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strlen	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:icatalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:enlist	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcpy	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncmp	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strchr	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:abort	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nl_langinfo	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:check_matching_with_multibyte_ops	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalnum	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.start	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswctype	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strncpy	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:strcoll	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcscoll	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.lifetime.end	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:mbrtowc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:nsubtoks	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towlower	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:charclass_index	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:memcmp	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wcrtomb	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctob	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswupper	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswlower	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:towupper	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_toupper_loc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:__ctype_tolower_loc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:wctype	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iswalpha	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfawarn	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalpha	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isupper	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:islower	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isdigit	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isxdigit	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isspace	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:ispunct	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isalnum	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isprint	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isgraph	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:iscntrl	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:isblank	default
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:llvm.dbg.value	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:usage	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.declare	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fprintf	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:dcgettext	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:printf	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fputs_unlocked	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:exit	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:main	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:set_program_name	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setlocale	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:bindtextdomain	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:textdomain	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:atexit	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:close_stdout	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getenv	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcmp	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:error	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xargmatch_internal	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strlen	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xrealloc	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcpy	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fopen	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__errno_location	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fread_unlocked	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fclose	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xstrtoumax	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:strcasecmp	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isatty	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:new_exclude	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:add_exclude	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:add_exclude_file	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:version_etc	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:proper_name	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xmalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:free	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:isdir	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:excluded_file_name	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepfile	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:open	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepdir	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:lseek	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:close	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__overflow	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fillbuf	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:memchr	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:grepbuf	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fwrite_unlocked	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:fflush_unlocked	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.start	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.lifetime.end	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__ctype_get_mb_cur_max	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:xalloc_die	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.memmove.p0i8.p0i8.i64	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:read	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getpagesize	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:abort	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:savedir	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:__xstat	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_mt_fct	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_rv_fct	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:color_cap_ne_fct	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:getopt_long	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.dbg.value	default
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:llvm.uadd.with.overflow.i64	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaerror	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.declare	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:error	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:abort	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:getenv	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_set_syntax	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfasyntax	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:memchr	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:realloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__errno_location	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dcgettext	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memcpy.p0i8.p0i8.i64	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_compile_pattern	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:xmalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strcpy	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:strlen	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaalloc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfacomp	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:free	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:EGexecute	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_get_mb_cur_max	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:mbtolower	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsexec	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:is_mb_middle	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfaexec	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_search	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:__ctype_b_loc	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:re_match	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfamusts	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsinit	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsprep	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:kwsincr	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.dbg.value	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.start	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.lifetime.end	default
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:llvm.memset.p0i8.i64	default
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile	default
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:error	default
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:dcgettext	default
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pexecute	default
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:abort	default
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:llvm.dbg.value	default
