</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:@kwsinit.trans	global
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:@match_icase	global
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:@mbtolower.out	global
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:@mbtolower.outalloc	global
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:@.str1	constant
</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:@__PRETTY_FUNCTION__.mbtolower	constant
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:@.str1	constant
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:@.str2	constant
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:@.str3	constant
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:@.str4	constant
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:@matchers	constant
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:@before_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:@after_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:@matchers	constant
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:@before_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/fgrep.ll>:@after_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:@matchers	constant
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:@before_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:@after_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:@kwset	global
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:@match_icase	global
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:@eolbyte	global
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:@match_words	global
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:@match_lines	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@syntax_bits_set	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@syntax_bits	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@case_fold	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@eolbyte	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@dfa	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@lexptr	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@lexleft	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@lasttok	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@laststart	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@parens	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@hard_LC_COLLATE	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@cur_mb_len	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@mbs	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@tok	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@depth	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str1	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@dfastate.letters	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@dfastate.newline	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@dfastate.initialized	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@dfaexec.sbit	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@dfaexec.sbit_init	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@mblen_buf	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@inputwcs	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@buf_end	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@buf_begin	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@dfamust.empty_string	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str2	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str3	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@__PRETTY_FUNCTION__.dfamust	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str4	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str5	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str6	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str7	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@using_utf8.utf8	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str8	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@minrep	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@maxrep	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@wctok	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str9	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@add_utf8_anychar.utf8_classes	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str10	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str11	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str12	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str13	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str14	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str15	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str16	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str17	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str18	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@parse_bracket_exp.zeroclass	global
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str19	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@__PRETTY_FUNCTION__.parse_bracket_exp	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str20	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str21	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str22	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str23	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str24	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str25	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str26	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str27	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@.str28	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:@prednames	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@stderr	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@program_name	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str1	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str2	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str3	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@before_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str4	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@matchers	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str5	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str6	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str7	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str8	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str9	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str10	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str11	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str12	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str13	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str14	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@after_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str15	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str16	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str17	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str18	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str19	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str20	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@stdout	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@eolbyte	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@filename_mask	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@max_count	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@out_before	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@out_after	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@only_matching	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str21	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str22	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str23	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@exit_failure	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str24	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@optarg	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str25	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@devices	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str26	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str27	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str28	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str29	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str30	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@no_filenames	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@binary_files	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@align_tabs	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@out_byte	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@count_matches	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str31	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@directories_args	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@directories_types	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@argmatch_die	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@directories	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@stdin	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str33	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@match_icase	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@list_files	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str34	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@out_line	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@exit_on_match	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@suppress_errors	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@out_invert	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@match_words	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@match_lines	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str35	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str36	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str37	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str38	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str39	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str40	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str41	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@color_option	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str42	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str43	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str44	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str45	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str46	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str47	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@show_help	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str48	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str49	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@excluded_patterns	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@excluded_directory_patterns	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@included_patterns	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@group_separator	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@line_buffered	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@label	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@done_on_match	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@out_quiet	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str50	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@context_match_color	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@selected_match_color	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str51	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str52	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str53	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str54	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@optind	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@compile	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@out_file	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@stats_base	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@errseen	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str55	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@filename	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str56	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@outleft	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@bufoffset	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@after_last_match	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@sep_color	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@sgr_start	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@sgr_end	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str57	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str58	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str59	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@filename_color	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str60	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@totalcc	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@lastout	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@totalnl	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@pending	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@bufbeg	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@buflim	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@lastnl	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str61	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str62	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@execute	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@selected_line_color	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@context_line_color	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str63	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str64	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@line_num_color	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@byte_num_color	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str65	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str66	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@prtext.used	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@buffer	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@pagesize	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@bufalloc	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@bufdesc	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str67	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str68	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str69	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str70	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@color_dict	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str71	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str72	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str73	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str74	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str75	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str76	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str77	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str78	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str79	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str80	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str81	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str82	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str83	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str84	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str85	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str86	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str87	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str88	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str89	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str90	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str91	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str92	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@get_nondigit_option.prev_digit_optind	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@short_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str94	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str95	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str96	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str97	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str98	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str99	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str100	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str101	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str102	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str103	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str104	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str105	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str106	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str107	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str108	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str109	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str110	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str111	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str112	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str113	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str114	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str115	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str116	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str117	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str118	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str119	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str120	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str121	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str122	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str123	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str124	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str125	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str126	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str127	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str128	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str129	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str130	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str131	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str132	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str133	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str134	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str135	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str136	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str137	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str138	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str139	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str140	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@long_options	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@setmatcher.matcher	global
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str141	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str142	constant
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:@.str143	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@dfawarn.mode	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@.str1	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@match_icase	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@eolbyte	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@patterns	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@pcount	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@.str2	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@match_words	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@match_lines	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@GEAcompile.line_beg_no_bk	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@GEAcompile.line_end_no_bk	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@GEAcompile.word_beg_no_bk	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@GEAcompile.word_end_no_bk	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@GEAcompile.line_beg_bk	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@GEAcompile.line_end_bk	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@GEAcompile.word_beg_bk	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@GEAcompile.word_end_bk	constant
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@dfa	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@kwset	global
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:@kwset_exact_matches	global
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:@.str	constant
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:@.str1	constant
