</home/lobo/repo/llvm-datalog/tests/grep/searchutils.ll>:kwsinit:29
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:kwsfree:8
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue:16
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:enqueue:17
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treedelta:22
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treefails:51
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext:17
</home/lobo/repo/llvm-datalog/tests/grep/kwset.ll>:treenext:18
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Gcompile:3
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Ecompile:3
</home/lobo/repo/llvm-datalog/tests/grep/grep.ll>:Acompile:3
</home/lobo/repo/llvm-datalog/tests/grep/egrep.ll>:Ecompile:3
</home/lobo/repo/llvm-datalog/tests/grep/kwsearch.ll>:Fcompile:62
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfasyntax:7
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaparse:101
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfaanalyze:636
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:merge:150
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:epsclosure:203
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfastate:1166
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:prepare_wc_buf:83
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:build_state:191
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfainit:34
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfacomp:776
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:dfafree:118
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:free_mbdata:81
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:transit_state_consume_1char:274
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:realloc_trans_if_necessary:67
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:addtok_mb:104
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:closure:507
</home/lobo/repo/llvm-datalog/tests/grep/dfa.ll>:setbit_case_fold:123
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:setmatcher:57
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prpending:51
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prline:241
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_line_head:259
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:print_offset:99
</home/lobo/repo/llvm-datalog/tests/grep/main.ll>:prtext:165
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:dfawarn:14
</home/lobo/repo/llvm-datalog/tests/grep/dfasearch.ll>:GEAcompile:234
</home/lobo/repo/llvm-datalog/tests/grep/pcresearch.ll>:Pcompile:4
